### ISSUE TITLE
`formats` are ignored in workflow

### ISSUE THREAD

**Issue by KevinRohn** [racklet/render-drawio-action#10]
Hi community,

I've noticed that the `formats` input parameters are ignored.
I can try every parameter I want, but it always just exports the files as `svg` files.

See output: 
![Bildschirmfoto 2021-07-22 um 13 41 54](https://user-images.githubusercontent.com/25847098/126634270-14e1e533-c81b-4e81-9a14-f220ce4943ab.png)

```yml
      - name: Render draw.io files
        uses: docker://ghcr.io/racklet/render-drawio-action:v1.0.3
        id: render
        with: # Showcasing the default values here
          formats: "png,pdf,svg" # 'png'
          sub-dirs: 'static/drawio/'
          # files: '' # unset, specify "dest-file:src-file" mappings here
          log-level: 'debug'
```
