### ISSUE TITLE
Formats are being ignored in the workflow and only SVG is being generated

### ISSUE THREAD

**Issue by jpeiffer** [racklet/render-drawio-action#18]
Example:
```yaml
      - name: Generate diagrams
        uses: docker://ghcr.io/racklet/render-drawio-action:v1.1.0
        id: render
        with:
          formats: "png,jpg"
          skip-dirs: ".git"
          sub-dirs: "."
```

Generated console:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/6424555/156069544-791b9d86-db9e-4876-9e63-5f9a8d9b4b4b.png">

Despite the formats being set as "png,jpg", the console seems to be implying that only `svg` was passed in, and that's what it's generating.

**Comment by zhai-lw** [comment]
try with this:
```yaml
- name: Render .drawio files
      uses: docker://ghcr.io/racklet/render-drawio-action:v1
      with: # Showcasing the default values here
        args: '"--sub-dirs=." "--skip-dirs=.git" "--files==" "--formats=png,pdf,jpg,svg" "--log-level=debug"'
      id: render
```
> Example:
> 
> ```yaml
>       - name: Generate diagrams
>         uses: docker://ghcr.io/racklet/render-drawio-action:v1.1.0
>         id: render
>         with:
>           formats: "png,jpg"
>           skip-dirs: ".git"
>           sub-dirs: "."
> ```
> 
> Generated console: <img alt="image" width="759" src="https://user-images.githubusercontent.com/6424555/156069544-791b9d86-db9e-4876-9e63-5f9a8d9b4b4b.png">
> 
> Despite the formats being set as "png,jpg", the console seems to be implying that only `svg` was passed in, and that's what it's generating.
