### ISSUE TITLE
produced output: Error: Export failed

### ISSUE THREAD

**Issue by 2pc** [racklet/render-drawio-action#22]
cannot gen jpg&png
use args 
```
- name: Render .drawio files
      uses: docker://ghcr.io/racklet/render-drawio-action:v1
      with: # Showcasing the default values here
        args: '"--sub-dirs=." "--skip-dirs=.git" "--files==" "--formats=png,pdf,jpg,svg" "--log-level=debug"'
      id: render
```
get "Export failed": produced output: Error: Export failed
```
{"level":"debug","msg":"Command \"/bin/sh -c \\\"/opt/drawio-desktop/runner-no-security-warnings.sh\\\" -x -t \\\"/github/workspace/flink/FLinkSQL.drawio\\\" -o \\\"/github/workspace/flink/FLinkSQL.jpg\\\" --no-sandbox\" produced output: Error: Export failed: /github/workspace/flink/FLinkSQL.drawio"}
```

**Comment by 2pc** [comment]
use  rlespinasse/drawio-export-action@v2   is ok 
```
name: Keep draw.io export synchronized
on:
  push:
    branches:
      master
    paths:
      "flink/*.drawio"
concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true
jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Export drawio files to asciidoctor and png files
        uses: rlespinasse/drawio-export-action@v2
        with:
          format: adoc
          transparent: true
          output: drawio-assets

      - name: Get author and committer info from HEAD commit
        uses: rlespinasse/git-commit-data-action@v1
        if: github.ref == 'refs/heads/master'

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          default_author: github_actor
          commit_message: "docs: sync draw.io exported files"
        if: github.ref == 'refs/heads/master'
```
